backend:
  name: git-gateway
  branch: main  # Ensure your branch is "main"

media_folder: "assets/"
public_folder: "/assets/"

collections:
  - name: "content"
    label: "Content"
    files:
      - file: "data/content.json"
        label: "Site Content"
        name: "content"
        fields:
          - { label: "Meta Title", name: "meta.title", widget: "string" }
          - { label: "Meta Description", name: "meta.description", widget: "string" }
          - { label: "Hero Headline", name: "hero.headline", widget: "string" }
          - { label: "Hero Video", name: "hero.video", widget: "string" }
          - { label: "Hero Image", name: "hero.image", widget: "image" }

  - name: "blog"
    label: "Blog Posts"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
