backend:
  name: git-gateway
  branch: main   # change to "master" if your repo uses that

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: ""   # optional: set your deployed site URL

collections:
  # -----------------
  # Quick edit: edit the whole JSON block inside content.md (code widget)
  # -----------------
  - name: "site_content_raw"
    label: "Site Content (Raw JSON)"
    files:
      - file: "content.md"
        label: "Content JSON (content.md)"
        name: "content_md"
        fields:
          - label: "Raw JSON"
            name: "body"
            widget: "code"
            default: "{}"
            pattern: "\\{"
            mode: "json"
            hint: "Edit the JSON block for the whole site. Save carefully."

  # -----------------
  # Recommended: structured content file for better CMS widgets
  # -----------------
  - name: "site_content_structured"
    label: "Structured Site Content (recommended)"
    files:
      - file: "data/content.json"
        label: "Structured site data (content.json)"
        name: "content_json"
        fields:
          - label: "Meta"
            name: "meta"
            widget: "object"
            fields:
              - { label: "Brand", name: "brand", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Headline", name: "headline", widget: "string" }
              - { label: "Subtext", name: "subtext", widget: "text" }
              - label: "CTA 1"
                name: "cta1"
                widget: "object"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Href", name: "href", widget: "string" }
              - label: "CTA 2"
                name: "cta2"
                widget: "object"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Href", name: "href", widget: "string" }
              - { label: "Video file", name: "video", widget: "string", required: false }
              - { label: "Image", name: "image", widget: "image", required: false }

          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "text" }
              - label: "Stats"
                name: "stats"
                widget: "list"
                field: { label: "Stat", name: "stat", widget: "string" }
              - { label: "Image", name: "image", widget: "image", required: false }

          - label: "USPs"
            name: "usps"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }

          - label: "Facilities"
            name: "facilities"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }

          - label: "Transformations"
            name: "transformations"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Before image", name: "before", widget: "image" }
              - { label: "After image", name: "after", widget: "image" }

          - label: "Trainers"
            name: "trainers"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }
              - { label: "Bio", name: "bio", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

          - label: "Schedule"
            name: "schedule"
            widget: "list"
            summary: "{{fields.day}}"
            fields:
              - { label: "Day name", name: "day", widget: "string" }
              - label: "Classes"
                name: "classes"
                widget: "list"
                fields:
                  - { label: "Time", name: "time", widget: "string" }
                  - { label: "Class", name: "class", widget: "string" }

          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Stars", name: "stars", widget: "number", value_type: "int" }
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

          - label: "Pricing"
            name: "pricing"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Price", name: "price", widget: "number", value_type: "float" }
              - label: "Features"
                name: "features"
                widget: "list"
                field: { label: "Feature", name: "feature", widget: "string" }
              - { label: "Popular", name: "popular", widget: "boolean", required: false }
              - label: "CTA"
                name: "cta"
                widget: "object"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Href", name: "href", widget: "string" }

          - label: "Offers"
            name: "offers"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Deadline (ISO)", name: "deadline", widget: "datetime" }
              - label: "CTA"
                name: "cta"
                widget: "object"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Href", name: "href", widget: "string" }

          - label: "Benefits"
            name: "benefits"
            widget: "list"
            field: { label: "Benefit", name: "benefit", widget: "string" }

          - label: "Blog"
            name: "blog"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Excerpt", name: "excerpt", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Href", name: "href", widget: "string" }

          - label: "FAQ"
            name: "faq"
            widget: "list"
            fields:
              - { label: "Question", name: "q", widget: "string" }
              - { label: "Answer", name: "a", widget: "text" }

          - label: "CTA"
            name: "cta"
            widget: "object"
            fields:
              - { label: "Headline", name: "headline", widget: "string" }
              - { label: "Address", name: "address", widget: "string" }
              - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Href", name: "href", widget: "string" }
